# Site settings
title: 호우의 블로그 
email: minho-choi@nhnent.com
description: > # this means to ignore newlines until "baseurl:"
 초보 개발자의 좌충우돌 블로그입니다.
baseurl: "/blog"
url: "http://Vnthf.github.io/blog" # the base hostname & protocol for your site
github_username:  Vnthf

# Build settings
markdown: kramdown
